### ISSUE TITLE
ReportState /Firebase and AC control

### ISSUE THREAD

**Issue by javiercuellar73** [googlecodelabs/smarthome-washer#31]
Hi Nick

Sorry for posting as an issue, but I couldn't find another place to contact you.

In your smarthome-washer you store the states of the devices in the firebase db, which triggers the ReportState to also store the same states.
Why not store directly to ReportState and when needed, read the state from ReportState? 

**Thanks for your help and comments.**

Best regards

Javier!!

**Comment by Fleker** [comment]
This is an implementation detail. You could probably get away with not using a database at all and only using the Home Graph for data state if you were clever.

I can explain my rationale for why I did design it the way I did. Some of it did start from someone else, but I was the one who cleaned up the code originally for release.

* It's easy to explain to beginners. If you know how to use Firebase, then this is just an extension of that knowledge. The Firebase console has a good view which shows data changing, to provide people with some knowledge that something is actually changing, and lets them debug in the database layer easily.
* Firebase provides realtime listeners for a web app which is really useful for custom consoles. The Home Graph API doesn't work in realtime, so I'd need to do polling or manual refreshing. This adds an extra layer of complexity to the codelab, which is meant to be easy to follow.
* While the codelab is nice to explain the core concepts of the API, I understand that it's probably not the architecture that will actually be used in a real product. Most smart devices have a companion app and some server infrastructure by the partner. As such, showing how to use the Home Graph as a database would not be useful for them. They already have a database.
* The Home Graph is not necessarily meant to be a full database for each partner. I have never checked the performance, but since I already have a Firebase instance for hosting and functions, I get the database as part of the bundle and should be pretty fast to access during the function execution.

**Comment by javiercuellar73** [comment]
Thanks a lot!!!!

**Comment by javiercuellar73** [comment]
Me again :). Another doubt. 
The **query intent** requests me (this is, I have to create a function to query the status from the device or from my database) to respond with its status.

If Google has that status, why doesn't it just bring that status and "auto-response" the query intent?

Thanks!!

**Comment by Fleker** [comment]
Ideally the Home Graph would have the complete up-to-date set of states for the device. At times, the canonical state may not be matching the Home Graph state for a potential variety of reasons. The explicit QUERY request is meant to be used to tell the server to grab the most up-to-date state of the device.

**Comment by javiercuellar73** [comment]
As fas as I understand, ReportState has been created to speed up the response time, but that doesn´t happen if we need to query our DB or the actual device state.  :S

**Comment by Fleker** [comment]
If the reported state data was considered reliable enough, then your fulfillment would not get a QUERY at all.

**Comment by javiercuellar73** [comment]
Ok, I understand. 
Thanks!!!!!
